manala:
  description: Elao - App Symfony Flex
  sync:
    - .manala/ansible .manala/ansible
    - .manala/docker .manala/docker
    - .manala/make .manala/make
    - .manala/.gitignore .manala/.gitignore
    - README.md .manala/README.md
