FROM debian:stretch-slim

LABEL maintainer="Elao <contact@elao.com>"

# System
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        curl \
        make \
        vim-tiny \
        gnupg2 dirmngr \
        openssh-client \
        sudo \
        git

# User
RUN adduser --disabled-password --gecos "" app \
    && echo "app ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/app

# Ssh
RUN echo "\
Host * \n\
  StrictHostKeyChecking no\n\
  HashKnownHosts        no\n\
  ForwardAgent          yes\n\
  UserKnownHostsFile    /dev/null\n\
  LogLevel              ERROR\n\
  AddKeysToAgent        yes\n" > /etc/ssh/ssh_config

# Ansible
RUN echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" > /etc/apt/sources.list.d/ansible.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        ansible

{{ if .system.php -}}
# Php
RUN echo "deb https://packages.sury.org/php/ stretch main" > /etc/apt/sources.list.d/php.list \
    && curl -sSL https://packages.sury.org/php/apt.gpg --output /etc/apt/trusted.gpg.d/php.gpg \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        php{{ .system.php.version }}-cli \
        php{{ .system.php.version }}-intl \
        php{{ .system.php.version }}-curl \
        php{{ .system.php.version }}-mbstring \
        php{{ .system.php.version }}-xml \
        php{{ .system.php.version }}-mysql \
        php{{ .system.php.version }}-zip \
    # Composer
    && curl -sSL https://getcomposer.org/installer | php -- --install-dir /usr/local/bin --filename composer
{{- end }}

# Node
RUN echo "deb https://deb.nodesource.com/node_10.x stretch main" > /etc/apt/sources.list.d/node.list \
    && curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key \
        | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && curl -sSL https://dl.yarnpkg.com/debian/pubkey.gpg \
        | apt-key add - \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        nodejs \
        yarn

WORKDIR /srv

USER app
