{{- $role := .role -}}

include \
	.manala/make/make.manala.mk \
	.manala/make/make.host.mk \
	.manala/make/make.travis.mk

#########
# Build #
#########

{{ range .role.distributions -}}
build.{{ . }}: .fail_if_host_not(local)
	docker build \
		--pull \
		--tag manala/ansible-role:{{ . }} \
		--file .manala/docker/Dockerfile.{{ . }} \
		.manala/docker
.PHONY: build.{{ . }}

{{ end -}}

######
# Sh #
######

MANALA_HELP += $(call if_host,local,$(SH_HELP)\n)

SH_HELP = \
	$(call help_section,Test host shell)

{{ range .role.distributions -}}
{{- $distribution := . | splitList "." -}}
SH_HELP += $(call help,sh.{{ . }}, Open shell on test host - {{ index $distribution 0 | title }} {{ index $distribution 1 | title }})
sh.{{ . }}: .fail_if_host_not(local) build.{{ . }}
	docker run \
		--rm \
		--tty --interactive \
		--privileged \
		--volume $(PWD):/srv/role \
		--volume $(PWD):/etc/ansible/roles/{{ $role.name }} \
		--workdir /srv/role \
		--hostname {{ $role.name }}.{{ . }} \
		--env USER_ID=$(MANALA_USER_ID) \
		--env GROUP_ID=$(MANALA_GROUP_ID) \
		--env MANALA_HOST=test \
		--env MANALA_VERBOSE=$(MANALA_VERBOSE) \
		--env DISTRIBUTION={{ . }} \
		--env DISTRIBUTION_ID={{ index $distribution 0 }} \
		--env DISTRIBUTION_RELEASE={{ index $distribution 1 }} \
		--env ANSIBLE_BECOME_FLAGS='-H -S -n -E' \
		--env ANSIBLE_RETRY_FILES_ENABLED=0 \
		--env ANSIBLE_FORCE_COLOR=1 \
		manala/ansible-role:{{ . }}
.PHONY: sh.{{ . }}

{{ end -}}

sh.%:
	$(call log_warning,Shell on \"$(*)\" is not supported)
.PHONY: sh

########
# Lint #
########

MANALA_HELP += $(call if_host,local,$(LINT_HELP_LOCAL)\n,$(LINT_HELP_TEST)\n)

LINT_HELP       = $(call help_section,Lint)
LINT_HELP_LOCAL = $(LINT_HELP) \
	$(call help,lint,               Lint role across distributions)
LINT_HELP_TEST  = $(LINT_HELP) \
	$(call help,lint,Lint role)

lint: .host_switch(lint)

lint@local: .fail_if_host_not(local)
	$(call list_loop,DISTRIBUTION,$(if $(DISTRIBUTIONS),$(DISTRIBUTIONS),$(ROLE_DISTRIBUTIONS)), \
		$$(call if_in,$$(DISTRIBUTION),$$(ROLE_DISTRIBUTIONS), \
			$$(call log,Lint \"$$(ROLE)\" on \"$$(DISTRIBUTION)\") ; \
				$$(call docker_make,lint@test), \
			$$(call log_warning,Lint \"$$(ROLE)\" on \"$$(DISTRIBUTION)\" is not supported) \
		) \
	)

lint@test: .fail_if_host_not(test)
	ansible-lint --force-color -v $(ROLE_DIR)

LINT_HELP_LOCAL += $(call if_in,debian.wheezy,$(ROLE_DISTRIBUTIONS),$(call help,lint.debian.wheezy, Lint role - Debian Wheezy))
lint.debian.wheezy: DISTRIBUTIONS = debian.wheezy
lint.debian.wheezy: lint@local

LINT_HELP_LOCAL += $(call if_in,debian.jessie,$(ROLE_DISTRIBUTIONS),$(call help,lint.debian.jessie, Lint role - Debian Jessie))
lint.debian.jessie: DISTRIBUTIONS = debian.jessie
lint.debian.jessie: lint@local

LINT_HELP_LOCAL += $(call if_in,debian.stretch,$(ROLE_DISTRIBUTIONS),$(call help,lint.debian.stretch,Lint role - Debian Stretch))
lint.debian.stretch: DISTRIBUTIONS = debian.stretch
lint.debian.stretch: lint@local

LINT_HELP_LOCAL += $(call if_in,centos.7,$(ROLE_DISTRIBUTIONS),$(call help,lint.centos.7,      Lint role - CentOS 7))
lint.centos.7: DISTRIBUTIONS = centos.7
lint.centos.7: lint@local

LINT_HELP_LOCAL += $(call if_in,ubuntu.xenial,$(ROLE_DISTRIBUTIONS),$(call help,lint.ubuntu.xenial, Lint role - Ubuntu Xenial))
lint.ubuntu.xenial: DISTRIBUTIONS = ubuntu.xenial
lint.ubuntu.xenial: lint@local

########
# Test #
########

TESTS = $(sort \
	$(foreach \
		TEST, \
		$(wildcard $(ROLE_TESTS_DIR)/*.yml), \
		$(if $(findstring .goss.,$(TEST)),, \
			$(patsubst /%,%,$(subst $(ROLE_DIR),,$(TEST))) \
		) \
	) \
)

tests/%.yml: FORCE
	$(call verbose, ,ANSIBLE_STDOUT_CALLBACK=actionable, ) \
		ansible-playbook $@ --extra-vars="test=$(subst .yml,,$(subst tests/,,$@))"
FORCE:

MANALA_HELP += $(call if_host,local,$(TEST_HELP_LOCAL),$(TEST_HELP_TEST))

TEST_HELP       = $(call help_section,Test)
TEST_HELP_LOCAL = $(TEST_HELP) \
	$(call help,test,               Test role across distributions)
TEST_HELP_BUILD = $(TEST_HELP) \
	$(call help,test,Test role)

test: .host_switch(test)

test@local: .fail_if_host_not(local)
	$(call list_loop,DISTRIBUTION,$(if $(DISTRIBUTIONS),$(DISTRIBUTIONS),$(ROLE_DISTRIBUTIONS)), \
		$$(call if_in,$$(DISTRIBUTION),$$(ROLE_DISTRIBUTIONS), \
		  $$(call log,Test \"$$(ROLE)\" on \"$$(DISTRIBUTION)\") ; \
				$$(call list_loop,TEST,$$(TESTS), \
					$$$$(call log,    $$$$(TEST)) ; \
						$$$$(call docker_make,$$$$(TEST)), \
					TRAVIS_FOLD \
				), \
			$$(call log_warning,Test \"$$(ROLE)\" on \"$$(DISTRIBUTION)\" is not supported) \
		) \
	)

test@test: .fail_if_host_not(test)
	$(call list_loop,TEST,$(TESTS), \
		$$(call log,Test \"$$(TEST)\") ; \
		$$(MAKE) $$(TEST) \
	)

TEST_HELP_LOCAL += $(call if_in,debian.wheezy,$(ROLE_DISTRIBUTIONS),$(call help,test.debian.wheezy, Test role - Debian Wheezy))
test.debian.wheezy: DISTRIBUTIONS = debian.wheezy
test.debian.wheezy: test@local

TEST_HELP_LOCAL += $(call if_in,debian.jessie,$(ROLE_DISTRIBUTIONS),$(call help,test.debian.jessie, Test role - Debian Jessie))
test.debian.jessie: DISTRIBUTIONS = debian.jessie
test.debian.jessie: test@local

TEST_HELP_LOCAL += $(call if_in,debian.stretch,$(ROLE_DISTRIBUTIONS),$(call help,test.debian.stretch,Test role - Debian Stretch))
test.debian.stretch: DISTRIBUTIONS = debian.stretch
test.debian.stretch: test@local

TEST_HELP_LOCAL += $(call if_in,centos.7,$(ROLE_DISTRIBUTIONS),$(call help,test.centos.7,      Test role - CentOS 7))
test.centos.7: DISTRIBUTIONS = centos.7
test.centos.7: test@local

TEST_HELP_LOCAL += $(call if_in,ubuntu.xenial,$(ROLE_DISTRIBUTIONS),$(call help,test.ubuntu.xenial, Test role - Ubuntu Xenial))
test.ubuntu.xenial: DISTRIBUTIONS = ubuntu.xenial
test.ubuntu.xenial: test@local
