include \
  .manala/make/make.color.mk \
  .manala/make/make.help.mk

include .manala/make/make.git.mk

##########
# Docker #
##########

include .manala/make/make.docker.mk

HELP += $(call help_section,Docker)
HELP += $(call help,docker.sh, Run shell)

docker.sh:
	$(call docker_sh)

###########
# Release #
###########

include .manala/make/make.release.mk

HELP += $(call help_section,Release)

{{ range $env, $options := .release }}
{{ if ne ($env | substr 0 1) "_" }}
HELP += $(call help,release@{{ $env }},Release in {{ $env }})
release@{{ $env }}:
	$(call release,{{ $env }})
{{ end }}
{{ end -}}

##########
# Deploy #
##########

include .manala/make/make.deploy.mk

HELP += $(call help_section,Deploy)

{{ range $env, $options := .deploy }}
{{ if ne ($env | substr 0 1) "_" }}
HELP += $(call help,deploy@{{ $env }},Deploy in {{ $env }})
deploy@{{ $env }}:
	$(call deploy,{{ $env }})
{{ end }}
{{ end -}}

###########
# Project #
###########

HELP += $(call help_section,Project)
